// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type jobsDao struct {
	*internal.JobsDao
}

var Jobs = &jobsDao{internal.NewJobsDao()}

// Add your custom methods below.
