// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type migrationsDao struct {
	*internal.MigrationsDao
}

var Migrations = &migrationsDao{internal.NewMigrationsDao()}

// Add your custom methods below.
