// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type passwordResetTokensDao struct {
	*internal.PasswordResetTokensDao
}

var PasswordResetTokens = &passwordResetTokensDao{internal.NewPasswordResetTokensDao()}

// Add your custom methods below.
