// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type sessionsDao struct {
	*internal.SessionsDao
}

var Sessions = &sessionsDao{internal.NewSessionsDao()}

// Add your custom methods below.
