// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type userScoresDao struct {
	*internal.UserScoresDao
}

var UserScores = &userScoresDao{internal.NewUserScoresDao()}

// Add your custom methods below.
