// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type usersDao struct {
	*internal.UsersDao
}

var Users = &usersDao{internal.NewUsersDao()}

// Add your custom methods below.
