// Code generated by cmd/gen. You may modify this file.
package dao

import (
	"go-gin/model/dao/internal"
)

type userDetailDao struct {
	*internal.UserDetailDao
}

var UserDetail = &userDetailDao{internal.NewUserDetailDao()}

// Add your custom methods below.
