// Code generated by cmd/gen. DO NOT EDIT.
package entity

import (
	"time"
)

type User struct {
	Id int `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Status *int `gorm:"column:status" json:"status"`
	CreatedAt *time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt *time.Time `gorm:"column:deleted_at" json:"deleted_at"`
	Age *int `gorm:"column:age" json:"age"`
}

func (e *User) TableName() string {
	return "user"
}
